bucket/FiraCode.json
Add `Fira Code` font.
> site: https://github.com/tonsky/FiraCode
=> Add Fira Code font version 1.206

bucket/FiraCode.json
- Upgrade Fira Code font version to 1.207.
- Fix remaining error that PR #13 left behind in issue #12 for FiraCode font.
=> Upgrade version to 1.207 and fix error in pwsh6

bucket/cascadia-code.json
=> Add Cascadia Code

bucket/Delugia-Code.json
This is Cascadia Code with included Nerd Fonts
https://github.com/adam7/delugia-code/blob/master/README.md
=> New Font Delugia-Code

bucket/Delugia-Nerd-Font.json
Used better Name (in preperation of adding delugia nerd font complete also (later)
=> Update and rename Delugia-Code.json to Delugia-Nerd-Font.json

bucket/Open-Sans.json
I wasn't sure what to set `version` to. Any ideas?
=> Add Open Sans

bucket/Raleway.json
=> Add Raleway

bucket/JetBrains-Mono.json
resolve: https://github.com/matthewjberger/scoop-nerd-fonts/issues/46
=> Add JetBrains Mono

bucket/JetBrains-Mono.json
=> JetBrains-Mono: Fix installation

bin/generate-manifests.ps1, bucket/CascadiaCode-NF.json
Official `CascadiaCode` nerd font, so `Delugia` becomes obsolete.
adam7/delugia-code#26
=> add cascadia code nerd font

bucket/SarasaGothic-CL.json, bucket/SarasaGothic-HK.json, bucket/SarasaGothic-J.json, bucket/SarasaGothic-K.json, bucket/SarasaGothic-SC.json, bucket/SarasaGothic-TC.json, bucket/SarasaGothic-ttc.json, bucket/SarasaGothic.json
SarasaGothic: Update to version 0.12.5
=> SarasaGothic: Update to version 0.12.5

bucket/FiraCode.json
Hopefully last one for this month :)
=> Update Fira Code to 5.2

bucket/Source-Han-Sans-HC.json, bucket/Source-Han-Sans-J.json, bucket/Source-Han-Sans-K.json, bucket/Source-Han-Sans-SC.json, bucket/Source-Han-Sans-TC.json
because the zip file structure has changed
=> change pattern for filter

bucket/Delugia-Mono-Nerd-Font-Complete.json, bucket/Delugia-Mono-Nerd-Font.json, bucket/Delugia-Nerd-Font-Book.json, bucket/Delugia-Nerd-Font-Complete.json
* updates Delugia Nerd Font to v2102.03.1
* add new Delugia Mono Nerd Font variants
=> add / update delugia nerd font

bucket/Delugia-Mono-Nerd-Font-Complete.json, bucket/Delugia-Mono-Nerd-Font.json, bucket/Delugia-Nerd-Font-Book.json, bucket/Delugia-Nerd-Font-Complete.json, bucket/Delugia-Nerd-Font.json
=> Update Delugia-Nerd-Font to 2102.25.1

bucket/SarasaGothic-ttc.json
Say sorry again, forget to modify ttc's hash
=> Modify sarasa-gothic-ttc's hash

bucket/Source-Han-Sans-HC.json, bucket/Source-Han-Sans-J.json, bucket/Source-Han-Sans-K.json, bucket/Source-Han-Sans-SC.json, bucket/Source-Han-Sans-TC.json
Since the zip file's structure of these fonts has changed.
Solves #113
=> Change filter's pattern of Source Han Sans font varianits

bucket/FiraCode-Script.json
Update the manifest according to https://github.com/matthewjberger/scoop-nerd-fonts/pull/120#issuecomment-877184383
=> FiraCode-Script: Rename and Update to Version 0.0.28

bucket/Open-Sans.json
=> Open-Sans@1: Hash fix

bucket/FiraCode.json, bucket/IPAex-Gothic.json, bucket/IPAex-Mincho.json, bucket/SarasaGothic-CL.json, bucket/SarasaGothic-HK.json, bucket/SarasaGothic-J.json, bucket/SarasaGothic-K.json, bucket/SarasaGothic-SC.json, bucket/SarasaGothic-TC.json, bucket/SarasaGothic-ttc.json, bucket/SarasaGothic.json
I notice some of manifests do not have `is_admin` check, which may cause unexpected result.
=> Fix missing is_admin check

bucket/andika.json
- Update `checkver.regex` to make autoupdate work
=> andika: Update to version 6.001

bucket/Lato.json
close #142.
This adds **Lato** to the bucket.
Additional info:
[homepage](https://www.latofonts.com/)
[Github source repo](https://github.com/latofonts/lato-source)
=> Add Lato font

bucket/Setofont.json
- Change URL from `dl.osdn.jp` to `osdn.dl.osdn.jp`
Close #147
=> Setofont@6.20: URL fix

bucket/Source-Han-Serif-HC.json, bucket/Source-Han-Serif-J.json, bucket/Source-Han-Serif-SC.json, bucket/Source-Han-Serif-TC.json
Update Source-Han-Serif version to 2.000
Add Source-Han-Serif-HC
=> Source-Han-Serif: Update to version 2.000

bucket/Anuphan.json
Change to : error \"Administrator rights are required to uninstall $app.\"
from: error \"Administrator rights are required to install $app.\"
=> Update Anuphan with better uninstall message.

bucket/FiraCode.json
https://github.com/tonsky/FiraCode/releases/tag/6
=> Update Fira Code to v6

bucket/FiraCode.json
https://github.com/tonsky/FiraCode/releases/tag/6.2
=> Update FiraCode to 6.2

bucket/SarasaGothic-CL.json, bucket/SarasaGothic-HK.json, bucket/SarasaGothic-J.json, bucket/SarasaGothic-K.json, bucket/SarasaGothic-SC.json, bucket/SarasaGothic-TC.json, bucket/Tiresias.json, bucket/andika-compact.json, bucket/andika-new-basic.json, bucket/andika.json
=> fix pre_install

bucket/Source-Han-Serif-HC.json, bucket/Source-Han-Serif-J.json, bucket/Source-Han-Serif-K.json, bucket/Source-Han-Serif-SC.json, bucket/Source-Han-Serif-TC.json
- Update `autoupdate.url` to make autoupdate work
=> Source-Han-Serif: Update to version 2.001

bucket/IBMPlexMono.json, bucket/IBMPlexSans-Arabic.json, bucket/IBMPlexSans-Condensed.json, bucket/IBMPlexSans-Devanagari.json, bucket/IBMPlexSans-Hebrew.json, bucket/IBMPlexSans-JP.json, bucket/IBMPlexSans-KR.json, bucket/IBMPlexSans-Thai-Looped.json, bucket/IBMPlexSans-Thai.json, bucket/IBMPlexSans.json, bucket/IBMPlexSerif.json
Adds IBM Plex to the bucket.
- IBM Plex Mono
- IBM Plex Sans
- IBM Plex Sans Arabic
- IBM Plex Sans Condensed
- IBM Plex Sans Devanagari
- IBM Plex Sans Hebrew
- IBM Plex Sans JP
- IBM Plex Sans KR
- IBM Plex Sans Thai
- IBM Plex Sans Thai Looped
- IBM Plex Serif
Github source repo:
- [IBM Plex](https://github.com/IBM/plex)
=> Add IBM Plex font

bucket/SarasaGothic-unhinted.json, bucket/SarasaGothic.json
=> SarasaGothic(-unhinted): Add notes about disk spaces

bucket/ChenYuLuoYen-Thin.json
**ChenYuLuoYen (辰宇落雁體)** is a Chinese (Traditional) font based on hand-written text of a high school student.
[Github repo](https://github.com/Chenyu-otf/chenyuluoyan_thin)
[news article (in Chinese)](https://udn.com/news/story/6898/6530121)
The **"Regular"** version of the font will be added in the future, according to [ReadMe](https://github.com/Chenyu-otf/chenyuluoyan_thin#%E5%85%B6%E4%BB%96%E5%8F%AF%E8%83%BD)
=> ChenYuLuoYen-Thin: Add version 1.0

README.md, bin/generate-manifests.ps1
=> (chore): update `genereate-manifests.ps1` to catch up recently changes

bucket/Hanamin.json
- Change URL from `dl.osdn.jp` to `osdn.dl.osdn.jp`
Same as #148
=> Hanamin@20170904: Fix url

bucket/smiley-sans-dev.json, bucket/smiley-sans.json
- smiley-sans: Add version 1.0.0
|             | Manifest                                                                                                                       |
| :---------- | :----------------------------------------------------------------------------------------------------------------------------- |
| Name        | smiley-sans                                                                                                                    |
| Version     | 1.0.0                                                                                                                          |
| Description | Smiley Sans(得意黑). A condensed and oblique Chinese typeface seeking a visual balance between the humanist and the geometric. |
| Homepage    | …
=> smiley-sans: Add version 1.0.0

bucket/LXGWNeoXiHei.json
=> LXGWNeoXiHei: Add version 1.007

bucket/Martian-Mono-otf.json, bucket/Martian-Mono.json
=> Martian-Mono(,-otf): Add version 1.0.0

bucket/Maple-Mono-NF.json, bucket/Maple-Mono-SC-NF.json, bucket/Maple-Mono-otf.json, bucket/Maple-Mono.json
=> Maple-Mono(,-otf,-NF,-SC-NF): Add version 6.2

bucket/LXGW-Bright-GB.json, bucket/LXGW-Bright-TC.json, bucket/LXGW-Bright.json
=> LXGW-Bright(,-GB,-TC): Fix Hash

bucket/Anuphan.json
=> Anuphan: Fix url & hash

bucket/SarasaGothic-CL.json, bucket/SarasaGothic-HK.json, bucket/SarasaGothic-J.json, bucket/SarasaGothic-K.json, bucket/SarasaGothic-SC.json, bucket/SarasaGothic-TC.json, bucket/SarasaGothic-ttc-unhinted.json, bucket/SarasaGothic-ttc.json, bucket/SarasaGothic-unhinted.json, bucket/SarasaGothic.json
=> SarasaGothic(-SC, -TC, ...): Fix installation and autoupdate, update to version 1.0.3

bucket/Open-Sans.json
=> Open-Sans: Fix url and license

bin/checkver.ps1
The upstream version: https://github.com/ScoopInstaller/Main/blob/master/bin/checkver.ps1
=> (chore): update scripts to match the upstream version

bucket/Noto-CJK-Mega-OTC.json
=> Noto-CJK-Mega-OTC: Update to version 2.004 and update upstream url to the new one
