matthewjberger/scoop-nerd-fonts

- bucket/Noto-CJK-Mega-OTC.json
- bucket/Source-Han-Mega-OTC.json
- bucket/Source-Han-Noto-CJK-Ultra-OTC.json
https://github.com/adobe-fonts/source-han-super-otc
https://blogs.adobe.com/CCJKType/2017/08/super-mega-ultra-otcs.html
> Anyway, a single-style/family OTC that combines all of its fonts is called a **Super OTC**. When multiple styles of the same family, such as Source Han Sans (36 fonts), Source Han Serif (28 fonts), and the Japanese-only Source Han Code JP (14 fonts), are combined into a single *OpenType Collection*, it is called a **Mega OTC**, and its name is therefore Source Han Mega OTC (78 fonts). By extension, the Noto CJK Mega OTC (64 fonts) includes Noto Sans CJK (36 fonts) and Noto Serif CJK (28 fonts).
> 
> We can take this to the next level, which is to combine the Source Han Mega OTC and Noto CJK Mega OTC into an even larger OpenType Collection with 142 fonts, called Source …
> Add Source Han & Noto CJK Mega/Ultra OTCs

- bucket/Hanamin.json
- bucket/Rounded-L-Mplus.json
- bucket/Rounded-Mplus.json
- bucket/Rounded-X-Mplus.json
- bucket/Setofont.json
- bucket/Tanuki-Permanent-Marker.json
- bucket/Wenquanyi-Microhei.json
- bucket/Wenquanyi-Zenhei.json
* Adding 8 CJK (Chinese-Japanese-Korean) Fonts
* **HanaMin** (花園明朝体) ([link](https://osdn.net/projects/hanazono-font/)) -- traditional serif printing font.
* **WenQuanYi Zhenhei** (文泉驿正黑) and **Microhei**(文泉驿微米黑) ([link](http://wenq.org)) -- serif font dedicated for on-screen display.
* **Tanuki Permanent Marker** (たぬき油性マジック) ([link](http://tanukifont.com/tanuki-permanent-marker/)) -- hand-written marker style font
* **SetoFont** (瀬戸フォント) ([link](https://osdn.net/projects/setofont/)) -- cute hand-written font
* **Rounded M+** ([link](http://jikasei.me/font/rounded-mplus/about.html)), Rounded-L M+ (less rounded version), and Rounded-X M+ (more rounded version). -- sans-serif font derived from the M+ font.
* All these fonts have a large character set, which can support most of the …
> Add 8 CJK Fonts

- bucket/Setofont.json
I forgot to change the font name in the prompt message for `uninstaller`. Sorry about that.
> Setofont: Fix typo in the prompt message

- bucket/SarasaGothic-CL.json
- bucket/SarasaGothic-HK.json
- bucket/SarasaGothic-J.json
- bucket/SarasaGothic-K.json
- bucket/SarasaGothic-SC.json
- bucket/SarasaGothic-TC.json
This adds 6 individual Sarasa font packages (region-specific) using the same file as `SarasaGothic`. The difference is that these regional-specific packages only extracts **a part of the font family** instead of all of them.
* The original **SarasaGothic** package contains 6 different sets of SarasaGothic, which represents different regional standards for glyphs. (SC: China mainland, TC: Taiwan, HK: Hong Kong, J: Japan, K: Korea, CL: Classic/16th century China)
* There are only slight differences in pen strokes between those standards. The picture below shows the difference of glyphs from Taiwan, HK, China, Japan and Korea.
* Users only need one of those `SarasaGothic` to show all the supported glyphs. That is, if you only installed `SarasaGothic TC`(Taiwan), The font can still be applied …
> Add region-specific SarasaGothic font packages

- bucket/SarasaGothic-CL.json
- bucket/SarasaGothic-HK.json
- bucket/SarasaGothic-J.json
- bucket/SarasaGothic-K.json
- bucket/SarasaGothic-SC.json
- bucket/SarasaGothic-TC.json
Sorry I was blind. :sweat:
I didn't realize there was a typo because `Scoop` just ignores the "depands" field (instead of showing some error).
> SarasaGothic fonts: fix typo

- bucket/IPAmj-Mincho.json
**IPAmj-Mincho** ([link](https://mojikiban.ipa.go.jp/1300.html)) is a free CJK (Chinese-Japanese-Korean) font with a large character set.
This font is designed to tackle with rare characters that only appears in person names, village names, historical documents, etc. It is maintained (and constantly updated) by Japanese government.
> IPAmj-Mincho: Add version 006.01

- bucket/SarasaGothic-CL.json
- bucket/SarasaGothic-HK.json
- bucket/SarasaGothic-J.json
- bucket/SarasaGothic-K.json
- bucket/SarasaGothic-SC.json
- bucket/SarasaGothic-TC.json
*Scoop* already has 7-zip installed initially. (The package `7-zip` exists in fresh install of *Scoop*) . Therefore we don't need `depends: "7-zip"` in the manifest.
> SarasaGothic: remove 'depends: 7-zip'

- bucket/FiraCode.json
Updates the Fira Code font to the latest version ([3.1](https://github.com/tonsky/FiraCode/releases/tag/3.1))
> Update Fira Code To Version 3.1

- bucket/FiraCode.json
Updates the Fira Code font to the latest version ([4](https://github.com/tonsky/FiraCode/releases/tag/4))
The naming of the .zip file changed (from `FiraCode_X.zip` to `Fira_Code_vX.zip`)
so I had to change the download link in the .json file for the HASH check and for the download ofc.
Autoupdate passed:
> Update Fira Code To Version 4

- bucket/CodeNewRoman-NF.json
- bucket/Gohu-NF.json
This PR contains two commits to update:
- CodeNewRoman-NF
- Gohu-NF
to version [2.1.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.1.0).
> Update CodeNewRoman-NF and Gohu-NF To Version 2.1.0

- bucket/FiraCode.json
Updates the FiraCode font to the latest version ([5](https://github.com/tonsky/FiraCode/releases/tag/5))
Autoupdate passed:
> FiraCode: Update To Version 5

- bucket/SarasaGothic-CL.json
- bucket/SarasaGothic-HK.json
- bucket/SarasaGothic-J.json
- bucket/SarasaGothic-K.json
- bucket/SarasaGothic-SC.json
- bucket/SarasaGothic-TC.json
- bucket/SarasaGothic-ttc.json
- bucket/SarasaGothic.json
Amendatory commit for [#108](https://github.com/matthewjberger/scoop-nerd-fonts/pull/108), bump versions and paths from `0.30.2` to `0.31.2`,   
excuse me for the first commit for scoop bucket.
> Bump sarasa's version to 0.31.2

- bucket/Source-Han-Sans-HC.json
- bucket/Source-Han-Sans-J.json
- bucket/Source-Han-Sans-K.json
- bucket/Source-Han-Sans-SC.json
- bucket/Source-Han-Sans-TC.json
update Source-Han-Sans to 2.004
now Source-Han-Sans do not put *.zip to repo, they put them in the release page.
> update Source-Han-Sans to 2.004

- bucket/Bai-Jamjuree.json
- bucket/Chakra-Petch.json
- bucket/Charm.json
- bucket/Charmonman.json
- bucket/Fahkwang.json
- bucket/K2D.json
- bucket/KoHo.json
- bucket/Kodchasan.json
- bucket/Krub.json
- bucket/Mali.json
- bucket/Niramit.json
- bucket/Sarabun.json
- bucket/Srisakdi.json
**National fonts**  are sets of freely-licensed computer fonts for the Thai script sponsored by the Thai government.
There are **13** typefaces in total. ([See Wikipedia for details](https://en.wikipedia.org/wiki/National_Fonts))
Notes:
* The manifest is modified from [Raleway.json](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/Raleway.json)
* Fonts are licensed under `OFL-1.1` according descriptions on Google Fonts.
> Add Thai national fonts

- bucket/Kanit.json
- bucket/Mitr.json
- bucket/Prompt.json
These 3 fonts: *Kanit*, *Mitr* and *Prompt* are modern loopless Thai typefaces that has simplified pen strokes. (similar concept to Sans-Serif fonts in Latin alphabets)
Notes:
* The manifest is modified from [Raleway.json](https://github.com/matthewjberger/scoop-nerd-fonts/blob/master/bucket/Raleway.json)
* Fonts are licensed under `OFL-1.1` according descriptions on Google Fonts.
> Add 3 Thai Loopless/Sans fonts

- bucket/FiraCode-iScript.json
close #96
[Fira Code iScript](https://github.com/kencrocken/FiraCodeiScript) is a font mashup to be used in code editors, displaying a script typeface for the italic font style. The Regular and Bold face styles are taken from [Fira Code](https://github.com/tonsky/FiraCode) and [Script12](https://www.myfontsfree.com/134618/script12pitchbt.htm).
Notes:
* **license** is marked as `OFL-1.1` according to **Fira Code** and **Script12** 's license.
> Add Fira Code iScript

- bucket/Soukou-Mincho.json
**[Soukou Mincho](http://flopdesign.com/blog/font/5228/) (装甲明朝)** is a **Japanese** and **Traditional Chinese** font with sharp penstrokes.
The name 'soukou' means armor.
Notes:
* The font is licensed as `OFL-1.1` according to [the developer's webpage](http://flopdesign.com/blog/font/5228/).
> Soukou-Mincho: Add version 1.0

- bucket/Tiresias.json
**Tiresias** ([Wikipedia](https://en.wikipedia.org/wiki/Tiresias_(typeface))) is a typeface designed for people with weak vision. It is developed by [The Royal National Institute for the Blind](https://www.rnib.org.uk/) (RNIB).
Notes:
* **file source**: The original homepage (http://tiresias.org/) is not maintained anymore. Also, I cannot find relative pages in the RNIB website. Therefore, I use [Debian package repo](https://packages.debian.org/buster/fonts-tiresias) as file source instead, since it is relatively stable.
* **homepage**:  using [Wikipedia](https://en.wikipedia.org/wiki/Tiresias_(typeface)) page as "homepage".
* The font's **license** is `GPL-3.0-or-later` according to Wikipedia and [official page in 2013 fetched from …
> Tiresias: Add version 0.1

- bucket/taipei-sans.json
**[Taipei Sans](https://sites.google.com/view/jtfoundry/en/ourproject)** is a sans-serif CJK (Chinese-Japanese-Korean) font.
Notes:
* The font is licensed with `OFL-1.1` according to [the developer's webpage](https://sites.google.com/view/jtfoundry/en/downloads?authuser=0).
> taipei-sans: Add version 1.000-beta

- bucket/jf-open-huninn.json
**[JF Open Huninn](https://github.com/justfont/open-huninn-font)** is a CJK (Chinese-Japanese-Korean) sans-serif font with **round curves**.
It is released by [JustFont](https://justfont.com/), a commercial font foundry in Taiwan, but as an open-source fontface.
The name 'hunnin' means boba (tapioca balls).
Notes:
* The font is licensed with `OFL-1.1` according to [the developer's webpage](https://github.com/justfont/open-huninn-font/blob/master/license.txt).
> jf-open-huninn: Add version 1.1

- bucket/Anuphan.json
**Anuphan** ([Github repo](https://github.com/cadsondemak/Anuphan)) is a Thai loopless font.
This font is the "free version" of **IBM Plex Thai Loopless**, which features the plex corner (round outside, sharp inside).
Notes:
* Read more about Author's documentation and process on [cadsondemak.com/ibm-plex-thai/](cadsondemak.com/ibm-plex-thai/)
> Anuphan: Add version 3.002

- bucket/Pattaya.json
**Pattaya** ([homepage](https://cadsondemak.github.io/pattaya/)) ([Github repo](https://github.com/cadsondemak/pattaya)) is the Thai version of [Lobster font](https://fonts.google.com/specimen/Lobster#standard-styles).
> Pattaya: Add version 2.000

- bucket/Sriracha.json
**Sriracha** is a Thai+Latin handwriting typeface, with an informal loopless + sans serif design.
([homepage](https://cadsondemak.github.io/sriracha/)) ([Github repo](https://github.com/cadsondemak/sriracha))
> Sriracha: Add version 1.002

- bucket/IPAex-Gothic.json
- bucket/IPAex-Mincho.json
**IPAmj Mincho** (previously added to this repo) is a free CJK font **maintained by Japanese government agency**. It covers a large set of characters.
This font has been recently replaced with **IPAex** font family.
(consists of 2 fonts: **IPAex Mincho** and **IPAex Gothic**)
Details about this upgrade can be found [here](https://moji.or.jp/ipafont/).
(It is written in Japanese. Sorry that I could not related essays written in English.)
> IPAmj-Mincho: Replace with IPAex fonts

- bucket/Hasklig.json
- Update `autoupdate.url` because the upstream repository's tag version change from `1.1` to `v1.2`
- Add `extract_dir` part because the zip file's structure has changed
> Hasklig: Update to version 1.2

- bucket/Delugia-Mono-Nerd-Font-Complete.json
- bucket/Delugia-Mono-Nerd-Font.json
- bucket/Delugia-Nerd-Font-Book.json
- bucket/Delugia-Nerd-Font-Complete.json
- bucket/Delugia-Nerd-Font.json
Since [version 2105.24.2](https://github.com/adam7/delugia-code/releases/tag/v2105.24.2), the download assets on Delugia's release page changed from `.ttf` font files to `.zip` files.
So I change the `url` and `autoupdate.url` of each Delugia's manifests accordingly.
Also add `extract_dir` part according to each zip file's structure.
> Delugia: Update to version 2106.17

- .editorconfig
- .github/workflows/issue.yml
- .github/workflows/issue_comment.yml
- .github/workflows/pull_request.yml
- .github/workflows/schedule.yml
Close #135
- Tweak `.editorconfig`, because `.yml` file are usually using 2 space as indentation.
- Currently, I do not set `GITH_MAIL` environment variable because I think commits made by CI does not count as contributions by anyone. But it is just my opinion 😊 and can be changed if needed.
Some information about `GITH_EMAIL` environment variable is not set, quote from [Ash258/Scoop-GithubActions's README](https://github.com/Ash258/Scoop-GithubActions/blob/stable-win/README.md#available-environment-variables)
>`GITH_EMAIL` environment variable is not required since [1.0.1](https://github.com/Ash258/Scoop-GithubActions/releases/tag/1.0.1), but it is recommended.
If email is not specified, commits will not be pushed using account bounded to the email. This will lead to not adding …
> Add `Ash258/Scoop-GithubActions` to do automated tasks

- bucket/LeagueMono-static.json
- bucket/LeagueMono-variable.json
* Requested in #101
* If there is any problem (or some other suggestions), please tell me. Or, merge this PR if you think the manifest looks fine to you. Thank you.
* **League Mono** is Sans-serif font **featuring variable character spaces**. Inspired by Fira Mono, Libertinus Mono, and Courier.
* The author provides 2 sets of the font:
**static**: 40 pre-defined styles. (for better compatibility)
**variable**: A single variable TTF font, which enables users to adjust font weight and char width **on-the-fly**. However, the feature may not be supported by some apps.
Therefore, I added some descriptions about the difference in the `notes` section. 
* Additional info:
[homepage](https://www.theleagueofmoveabletype.com/league-mono)
[Github source …
> LeagueMono(-static)(-variable): Add version 2.220

- bucket/Open-Sans.json
The downloaded file will have different hash each time, similar to the past issue of Raleway (#80) which fixed by make it nightly (c11fce3df0d3e900a4dcece4f71d193311a26bd2)
> Make Open-Sans nightly

- bucket/SarasaGothic-CL.json
- bucket/SarasaGothic-HK.json
- bucket/SarasaGothic-J.json
- bucket/SarasaGothic-K.json
- bucket/SarasaGothic-SC.json
- bucket/SarasaGothic-TC.json
- bucket/Tiresias.json
- bucket/andika-compact.json
- bucket/andika-new-basic.json
- bucket/andika.json
A minor refactor, move pre-install scripts (the scripts above the line `$currentBuildNumber = [int] ...`) into the `pre_install` section
> Move pre-install scripts to `pre_install` section

- bucket/SarasaGothic-CL.json
- bucket/SarasaGothic-HK.json
- bucket/SarasaGothic-J.json
- bucket/SarasaGothic-K.json
- bucket/SarasaGothic-SC.json
- bucket/SarasaGothic-TC.json
This will avoid 7-zip extraction error for users whose **Scoop directory** contains spaces.
(e.g. `C:\Users\John Smith\scoop`)
> SarasaGothic: Fix issue in 'path with spaces'

- bucket/HakushuGyosyoOiwai.json
- bucket/HakushuKaisyoOiwai.json
These fonts are designed to be used in celebrations, banquets, etc.
**NOTES:**
* Autoupdate is not needed because last update was in 2005.
* license: The terms can be found in the bottom of the download page
```
【使用方法】
商業使用ＯＫですが、あらかじめ[お問合せフォーム](http://www.hakusyu.com/contact.htm)よりご連絡下さい。 個人使用の場合は必要ありません。
印章関連の商業使用は禁止します。
文字種はお祝用文字に限定されています。
著作権は株式会社白舟書体が保有します。
これらのフォントをご使用になった結果もし損害が生じても、弊社は一切責任を負いません。
無料版でもっと文字種を増やしてほしいというご希望にはお答えできません。
```
This translates to:
```
[Terms of Use]
It is Okay to use the font commercially. However please [contact us](http://www.hakusyu.com/contact.htm) beforehand. There is no need to contact for personal use.
Commercial use of this font in stamps/logos is forbidden.
For kanji (Chinese character), we will only add kanjis that will be used in celebrations. …
```
> Add 2 Hakushu(白舟) Japanese fonts

- bucket/LXGW-Bright-Classic.json
- bucket/LXGW-Bright.json
* closes #184
* **[LXGW Bright](https://github.com/lxgw/LxgwBright)** is an open-source Chinese font. The font is a combination of **LXGW WenKai** Lite/TC (霞鹜文楷 Lite/TC) and **Ysabeau Office**.
**NOTES**:
* **Naming** of the packages: I named the package as `LXGW-Bright` because the app name (in this case, font name) is `LXGW Bright`. This Follows the convention of *Main* and *Extras* buckets.
* Downloading **independent OTF** files (instead of the archive of whole repo in [releases page](https://github.com/lxgw/LxgwBright/releases)) to avoid **space bloat**.
I think this is fine because the developer will change the version number **every time** when one of the font file updates. See [file history](https://github.com/lxgw/LxgwBright/commits/main/OTF/LXGWBright-Italic.otf) and [release …
> LXGW-Bright(-Classic): Add version 2.152

- bucket/Soukou-Mincho.json
Currently, the entire http://flopdesign.com website can not be accessed.
So I change the download link to https://fontmeme.com/fonts/download/222487/soukou-mincho.zip
And we should change download url back to original https://www.flopdesign.com/images/datafont/flopdesign-op/SoukouMincho-Font.zip when the flopdesign website can be accessed.
> Soukou-Mincho: Fix url

- bucket/andika-compact.json
- bucket/andika-new-basic.json
- bucket/andika.json
It seems that the compact variant of andika font no longer have any update.
> (chore): remove andika-compact's autoupdate settings

- bucket/Plus-Jakarta-Sans.json
[+Jakarta Sans](https://github.com/tokotype/PlusJakartaSans) is a open-source fonts. Designed for Jakarta "City of collaboration" program in 2020.
Closes #197
> Plus-Jakarta-Sans: Add version 2.6

- bin/generate-manifests.ps1
[nerd-fonts just release a newer version 2.3.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.0), and I'm curious if there are new font added in this release.
Eventually, I come up with a one-liner to do that, and I think it's worth to put this command into a comment for the future contributors (including future me 🤣)
P.S. It turns out no new font were added in 2.3.0
> (chore): add tips to generate $fontNames list from nerd-fonts latest release

- bucket/jf-open-huninn.json
As the release asset is now a single .ttf file instead of a .zip file, this PR updates `autoupdate` and removes `extract_dir` accordingly.
> jf-open-hunnin: Update to version 2.0

- bucket/GlowSansJ-Compressed.json
- bucket/GlowSansJ-Condensed.json
- bucket/GlowSansJ-Extended.json
- bucket/GlowSansJ-Normal.json
- bucket/GlowSansJ-Wide.json
- bucket/GlowSansSC-Compressed.json
- bucket/GlowSansSC-Condensed.json
- bucket/GlowSansSC-Extended.json
- bucket/GlowSansSC-Normal.json
- bucket/GlowSansSC-Wide.json
- bucket/GlowSansTC-Compressed.json
- bucket/GlowSansTC-Condensed.json
- bucket/GlowSansTC-Extended.json
- bucket/GlowSansTC-Normal.json
- bucket/GlowSansTC-Wide.json
This PR adds the following 15 font manifests:
- GlowSansJ-Compressed
- GlowSansJ-Condensed
- GlowSansJ-Extended
- GlowSansJ-Normal
- GlowSansJ-Wide
- GlowSansSC-Compressed
- GlowSansSC-Condensed
- GlowSansSC-Extended
- GlowSansSC-Normal
- GlowSansSC-Wide
- GlowSansTC-Compressed
- GlowSansTC-Condensed
- GlowSansTC-Extended
- GlowSansTC-Normal
- GlowSansTC-Wide
Close #246
> GlowSans(J,SC,TC): Add version 0.93

- bucket/Victor-Mono.json
Resolves #277
This PR changes the download URL from:
https://rubjo.github.io/victor-mono/VictorMonoAll.zip
to:
https://raw.githubusercontent.com/rubjo/victor-mono/v1.5.6/public/VictorMonoAll.zip
to avoid potential `hash check failed` issues.
> Victor-Mono: Change download url to fix hash issues

- bucket/Bai-Jamjuree.json
- bucket/Chakra-Petch.json
- bucket/Charm.json
- bucket/Charmonman.json
- bucket/Fahkwang.json
- bucket/K2D.json
- bucket/Kanit.json
- bucket/KoHo.json
- bucket/Kodchasan.json
- bucket/Krub.json
- bucket/Mali.json
- bucket/Mitr.json
- bucket/Niramit.json
- bucket/Prompt.json
- bucket/Raleway.json
- bucket/Sarabun.json
- bucket/Srisakdi.json
This PR changes the download URL from the Google Fonts site to GitHub, because the original mechanism, downloading through a URL like `https://fonts.google.com/download?family=Raleway#/fonts.zip`, no longer work as excepted.
- Bai-Jamjuree: Fix url
- Chakra-Petch: Fix url
- Charm: Fix url
- Charmonman: Fix url
- Fahkwang: Fix url
- K2D: Fix url
- Kanit: Fix url
- KoHo: Fix url
- Kodchasan: Fix url
- Krub: Fix url
- Mali: Fix url
- Mitr: Fix url
- Niramit: Fix url
- Prompt: Fix url
- Raleway: Fix url
- Sarabun: Fix url
- Srisakdi: Fix url
Resolves #290
> Many: Fix url

- bucket/IPAex-Gothic.json
- bucket/IPAex-Mincho.json
The `IPA` license is officially listed on SPDX's website (https://spdx.org/licenses/).
Therefore, we can simplify the license field.
> (chore): simplify `IPA` license field

- bucket/Open-Sans.json
An error occurred while trying to install Open-Sans fonts due to a pair of characters in the URL: `[` and `]` are now not understood by github.
> Open-Sans: Fix url

- bucket/Klee-One.json
[Klee One](https://github.com/fontworks-fonts/Klee)
Klee is a script font handwritten by pencil or pen. It's quiet design has an elegant look that sets itself apart from traditional script and textbook fonts. Ideal for body text. [Learn more](https://fontworks.co.jp/fontsearch/KleePro-M/).
> Klee-One: Add version 1.000
